### ISSUE TITLE
Protocol org.apache.coyote.http11.Http11NioProtocol:443 has different KeyStore file

### ISSUE THREAD

**Issue by Panallox** [valb3r/letsencrypt-helper#14]
I've been trying all day to try and get this working but I keep encountering the same issue. I've setup my `application.properties` file as below:

```
server.port=443
server.ssl.enabled=true
server.ssl.protocol=TLS
server.ssl.key-store=/path/to/custom/file.keystore
server.ssl.key-store-type=pkcs12
server.ssl.key-store-password=xxx
server.ssl.key-alias=name

lets-encrypt-helper.domain=xxx
lets-encrypt-helper.contact=xxx
```

When the application boots up it seems to get to:

```
    var sslConfig = Arrays.stream(protocol.findSslHostConfigs())
        .filter(it -> null != it.getCertificateKeystoreFile())
        .filter(it -> it.getCertificateKeystoreFile().contains(serverProperties.getSsl().getKeyStore()))
        .filter(it -> serverProperties.getSsl().getKeyStorePassword().equals(it.getCertificateKeystorePassword()))
        .findFirst()
        .orElse(null);
```

And this method chain always returns null. I added the class file to my project, added additional logging and rebuilt and by printing out the value of the SSL host configs I get:

```
Keystore file for _default_ (protocols TLSv1,TLSv1.3,TLSv1.2,SSLv2Hello,TLSv1.1) = null
```

Where `_default_` is the SSL host config `getHostName()`. I've followed all the steps verbatim from the readme but I'm unable to work out how to fix this problem. Do you have any idea whether additional configuration is needed? I even generated a dummy certificate with the matching alias name but it still produces a `null` keystore file.

**Edit**

Worth noting that this is Spring Boot 4.7.2

Thanks

**Comment by valb3r** [comment]
@Panallox `Spring Boot 4.7.2` - Maximum version of Spring Boot is 3.0 (unreleased as of now), Spring framework also does not have 4.7.2 version - latest of 4.x branch is 4.3.x. Can you please clarify versions?

**Comment by valb3r** [comment]
Assuming you meant Spring Boot 2.7.2, the fix is in https://github.com/valb3r/letsencrypt-helper/pull/15

**Comment by Panallox** [comment]
Sorry yes I meant 2.7.2, spent too long coding and must have got frazzled! Excellent work, thanks for taking care of this 😄
