### ISSUE TITLE
Upgrade to Spring Boot 3

### ISSUE THREAD

**Issue by suchorski** [valb3r/letsencrypt-helper#18]
Hi, this lib will be upgraded to Spring Boot 3?

**Comment by valb3r** [comment]
Hi, yes, sometime later when Spring Boot 3 will be more widespread

**Comment by suchorski** [comment]
Nice.. thanks!

**Comment by valb3r** [comment]
@suchorski New release supports Spring Boot 3.x

**Comment by suchorski** [comment]
Very nice... Will take a look, thanks
