### ISSUE TITLE
Is that support for spring boot 3?

### ISSUE THREAD

**Issue by bishwajitcse** [valb3r/letsencrypt-helper#20]
I am getting this message when trying with spring boot 3.0.4:

An attempt was made to call a method that does not exist. The attempt was made from the following location:

    com.github.valb3r.letsencrypthelper.tomcat.TomcatWellKnownLetsEncryptChallengeEndpointConfig.matchesCertFilePathAndPassword(TomcatWellKnownLetsEncryptChallengeEndpointConfig.java:252)

The following method did not exist:

    'java.lang.String org.apache.tomcat.util.net.SSLHostConfig.getCertificateKeystoreFile()'

The calling method's class, com.github.valb3r.letsencrypthelper.tomcat.TomcatWellKnownLetsEncryptChallengeEndpointConfig, was loaded from the following location:

    jar:file:/app.jar!/BOOT-INF/lib/letsencrypt-helper-tomcat-0.2.5.jar!/com/github/valb3r/letsencrypthelper/tomcat/TomcatWellKnownLetsEncryptChallengeEndpointConfig.class

The called method's class, org.apache.tomcat.util.net.SSLHostConfig, is available from the following locations:

    jar:file:/app.jar!/BOOT-INF/lib/tomcat-embed-core-10.1.5.jar!/org/apache/tomcat/util/net/SSLHostConfig.class

The called method's class hierarchy was loaded from the following locations:

    org.apache.tomcat.util.net.SSLHostConfig: jar:file:/app.jar!/BOOT-INF/lib/tomcat-embed-core-10.1.5.jar!/

**Comment by valb3r** [comment]
No, Spring Boot 3 is not supported yet

**Comment by valb3r** [comment]
Supported now
