### ISSUE TITLE
Does it support different port than 443 ?

### ISSUE THREAD

**Issue by Blackbirrrd** [valb3r/letsencrypt-helper#29]
Hello,
I'm trying to use the lib on my spring boot app but this app run on port 8443 because I already have an apache server running on port 443
When I run the app I have an error because it can't reach the service without adding the port number after the domain name

Invalid response from https://my_domain/.well-known/acme-challenge/KMTJqv3wHu-ZjGMBzPIyRKWQyM0ql53n2Bc-LDpxC7E: 404

Do you know if it's possible to force the acme4j library to add a port number while challenging for authorization ?

**Comment by valb3r** [comment]
@Blackbirrrd For challenge port 80 is used and it must be open to public, it can't be changed. For actual HTTPS traffic you can use any port you want - `server.port` configuration property of Spring is responsible for that
